# Generated by Django 4.0.3 on 2022-05-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmissionPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionconditionagreement',
            name='response',
            field=models.IntegerField(choices=[(1, 'yes'), (2, 'no')], default=2, verbose_name='response'),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file_type',
            field=models.PositiveIntegerField(choices=[(1, 'cover letter'), (2, 'manuscript'), (3, 'supplementary data')], verbose_name='file type'),
        ),
    ]
