# Generated by Django 4.0.3 on 2022-07-09 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Journals', '0001_initial'),
        ('Contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manuscripts', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='subject_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manuscripts', to='Journals.journalsubjectarea'),
        ),
        migrations.AddConstraint(
            model_name='manuscriptsection',
            constraint=models.UniqueConstraint(fields=('section', 'manuscript'), name='unique_section'),
        ),
        migrations.AddConstraint(
            model_name='manuscriptkeywordtag',
            constraint=models.UniqueConstraint(fields=('tag', 'manuscript'), name='unique_tag'),
        ),
        migrations.AddConstraint(
            model_name='manuscriptfile',
            constraint=models.UniqueConstraint(fields=('file_type', 'label_no', 'manuscript'), name='unique_manuscript_file'),
        ),
        migrations.AddConstraint(
            model_name='manuscriptauthor',
            constraint=models.UniqueConstraint(fields=('rank', 'manuscript', 'email'), name='unique_author'),
        ),
        migrations.AddIndex(
            model_name='manuscript',
            index=models.Index(fields=['title'], name='title_idx'),
        ),
    ]
