# Generated by Django 4.0.3 on 2022-05-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contents', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='manuscriptfile',
            constraint=models.UniqueConstraint(fields=('file_type', 'label_no', 'manuscript'), name='unique_manuscript_file'),
        ),
    ]
