# Generated by Django 4.0.3 on 2022-05-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubmissionPortal', '0001_initial'),
        ('PeerReviewPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalsubmission',
            name='author_submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_submission', to='SubmissionPortal.authorsubmission'),
        ),
    ]
