# Generated by Django 4.0.3 on 2022-05-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerReviewPortal', '0002_alter_journalsubmission_author_submission'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='editorreport',
            name='unique_editor_report',
        ),
        migrations.RemoveField(
            model_name='editorreport',
            name='report',
        ),
        migrations.AddField(
            model_name='editorreport',
            name='details',
            field=models.TextField(default='', verbose_name='report_details'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='editorreport',
            constraint=models.UniqueConstraint(fields=('details', 'editor', 'journal_submission'), name='unique_editor_report'),
        ),
    ]
