# Generated by Django 4.0.3 on 2022-05-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PeerReviewPortal', '0003_remove_editorreport_unique_editor_report_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewerreportsection',
            options={'ordering': ('created_at',), 'verbose_name': 'reviewer_report_section', 'verbose_name_plural': 'reviewer_report_sections'},
        ),
    ]
