# Generated by Django 4.0.3 on 2022-08-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='journalsubjectarea',
            constraint=models.UniqueConstraint(fields=('name', 'journal'), name='unique_journal_subject_areas'),
        ),
    ]
