# Generated by Django 4.0.3 on 2022-05-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='issn',
            field=models.CharField(default='', max_length=255, verbose_name='issn'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalbanner',
            name='section',
            field=models.IntegerField(choices=[(1, 'main'), (2, 'middle'), (3, 'bottom')], default=1, verbose_name='section'),
        ),
    ]
