# Generated by Django 4.0.3 on 2022-08-06 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cores', '__first__'),
        ('Journals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_applications', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalvolumeissue',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='Journals.journalvolume'),
        ),
        migrations.AddField(
            model_name='journalvolume',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='journalviewlog',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='journalviewlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalsubjectarea',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='journalreportquestion',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_questions', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='journalpermission',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='journaldetail',
            name='detail_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cores.journaldetailtype'),
        ),
        migrations.AddField(
            model_name='journaldetail',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='journalbanner',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='journal',
            name='subject_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='Cores.subjectdiscipline'),
        ),
        migrations.AddField(
            model_name='editorialmember',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_roles', to='Journals.editor'),
        ),
        migrations.AddField(
            model_name='editorialmember',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_members', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='editorialmember',
            name='permissions',
            field=models.ManyToManyField(related_name='journal_roles', to='Journals.journalpermission'),
        ),
        migrations.AddField(
            model_name='editor',
            name='journals',
            field=models.ManyToManyField(related_name='editors', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='editor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
