# Generated by Django 4.0.3 on 2022-09-18 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Journals', '0001_initial'),
        ('Cores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_applications', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalvolumeissue',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='Journals.journalvolume'),
        ),
        migrations.AddField(
            model_name='journalvolume',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='journalviewlog',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='journalviewlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalsubjectarea',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='journalreportquestion',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_questions', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='journalpermission',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='journalinformation',
            name='heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cores.informationheading'),
        ),
        migrations.AddField(
            model_name='journalinformation',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='journalbanner',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='journal',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='Cores.discipline'),
        ),
        migrations.AddField(
            model_name='editorjournalactivity',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_activites', to='Journals.editor'),
        ),
        migrations.AddField(
            model_name='editorjournalactivity',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_activites', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='editorialmember',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_roles', to='Journals.editor'),
        ),
        migrations.AddField(
            model_name='editorialmember',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_members', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='editorialmember',
            name='permissions',
            field=models.ManyToManyField(related_name='journal_roles', to='Journals.journalpermission'),
        ),
        migrations.AddField(
            model_name='editor',
            name='journals',
            field=models.ManyToManyField(related_name='editors', through='Journals.EditorJournalActivity', to='Journals.journal'),
        ),
        migrations.AddField(
            model_name='editor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='journalsubjectarea',
            constraint=models.UniqueConstraint(fields=('name', 'journal'), name='unique_journal_subject_areas'),
        ),
        migrations.AddConstraint(
            model_name='journalinformation',
            constraint=models.UniqueConstraint(fields=('heading', 'journal'), name='unique_journal_headings'),
        ),
        migrations.AddConstraint(
            model_name='editorjournalactivity',
            constraint=models.UniqueConstraint(fields=('editor', 'journal'), name='unique_editor_journal_activities'),
        ),
    ]
