# Generated by Django 4.0.3 on 2022-09-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='editorjournalactivity',
            table='editor_journal_activities',
        ),
    ]
