# Generated by Django 4.0.3 on 2022-08-28 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0002_journalsubjectarea_unique_journal_subject_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialmember',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_roles', to='Journals.editor'),
        ),
    ]
