# Generated by Django 4.0.3 on 2022-07-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0002_alter_journal_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='subject_dicipline',
            new_name='subject_discipline',
        ),
    ]
