# Generated by Django 4.0.3 on 2022-09-18 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0003_alter_editorjournalactivity_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorjournalactivity',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_activities', to='Journals.editor'),
        ),
        migrations.AlterField(
            model_name='editorjournalactivity',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_activities', to='Journals.journal'),
        ),
        migrations.AlterField(
            model_name='editorjournalactivity',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 13, 59, 17, 261473, tzinfo=utc), verbose_name='last_login'),
        ),
    ]
