# Generated by Django 4.0.3 on 2022-07-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0003_rename_subject_dicipline_journal_subject_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialmember',
            name='access_login',
            field=models.CharField(default='', max_length=255, verbose_name='access_login'),
            preserve_default=False,
        ),
    ]
