# Generated by Django 4.0.3 on 2022-07-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0004_editorialmember_access_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='affiliation',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='affiliation'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='specialisation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='specialisation'),
        ),
    ]
