# Generated by Django 4.0.3 on 2022-07-31 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "Journals",
            "0005_alter_editor_affiliation_alter_editor_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "processing"),
                            (2, "accept"),
                            (3, "rejected"),
                            (4, "completed"),
                        ],
                        default=1,
                        verbose_name="recruitment_status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editor_recruitment_applications",
                        to="Journals.journal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editorial_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "editor recruitment application",
                "verbose_name_plural": "editor recruitment applications",
                "db_table": "editor_recruitment_applications",
                "ordering": ["-created_at"],
            },
        ),
    ]
